apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-waves-demo
spec:
  project: default
  source:
    repoURL: https://github.com/rcorderoayigroup/sync-waves-demo.git
    path: sync-waves-demo
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
